#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_dot.dot import Dot

plugin = 'rqt_dot'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))#, plugin_argument_provider=Dot.add_arguments))
